import { BoxBrandType } from './box-brand/boxBrand';
import { ClientType } from './client';
import { CuttingType } from './cuttingType';
import { ExportSentType } from './exportSent';
import { HarborType } from './harbor';
import { BusinessType } from './merchant/business';
import { MerchantResponse } from './merchant/merchant.response';

export type ExportType = {
  id: number | '';
  cuttingDate: Date | '';
  weekDescription: string;
  weekDaysOfWeek: string[] | null;
  weekBoxesOfDay: number[];
  weekTotal: number;
  boxQuantity: number | '';
  boxBrand: Partial<BoxBrandType>;
  boxBrandId: number | '';
  cuttingType: Partial<CuttingType>;
  cuttingTypeId: number | '';
  merchant: Partial<MerchantResponse>;
  merchantId: number | '';
  business: Partial<BusinessType>;
  businessId: number | '';
  harborDeparture: Partial<HarborType>;
  harborDestination: Partial<HarborType>;
  client: Partial<ClientType>;
  clientId: number | '';
  shipName: string;
  estimatedTravelTime: string;
  bookingNumber: string;
  shippingDateTime: Date | '';
  shippingCompanyId: number;
  departureHarborId: number;
  destinationHarborId: number;
  depositId: number;
  transportId: number;
  verifierId: number;
  pendingExportSent: boolean;
  exportSent: Partial<ExportSentType>;
};
