export const MATERIAL_TYPE_ORDER: string[] = [
  'BOTTOM',
  'LID',
  'COVER',
  'CARDBOARD',
  'PARASEAL',
  'PAD',
  'SPONGE',
  'PALLET',
  'MINI_PALLET',
  'CORNER',
  'REINFORCEMENT',
  'PACKING_TAPE',
  'LABEL',
  'BAND',
  'SACCHET',
  'RUBBER',
  'PROTECTOR',
  'CLUSTER_BAG',
  'STAPLE',
  'STRIPPING',
  'THERMOGRAPH',
  'SEAL',
  'METTO_LABEL',
  'LATEX_REMOVER',
  'BLOCKING_SHEET',
  'PESTICIDE',
  'INSECTICIDE',
  'STICKER',
  'SHEET',
  'CONTAINER_SEAL_PLASTIC',
  'SECURITY_KIT',
  'BOARDING_CARD',
];

export const MATERIAL_TYPE_LABELS: Record<string, string> = {
  BOTTOM: 'Fondo',
  LID: 'Tapa',
  COVER: 'Funda',
  CARDBOARD: 'Cartulina',
  PARASEAL: 'Paraseal',
  PAD: 'Pad',
  SPONGE: 'Esponja',
  PALLET: 'Pallet',
  MINI_PALLET: 'Mini Pallet',
  CORNER: 'Esquinero',
  REINFORCEMENT: 'Refuerzo',
  PACKING_TAPE: 'Cinta de Embalaje',
  LABEL: 'Etiqueta',
  BAND: 'Banda',
  SACCHET: 'Sachet',
  RUBBER: 'Liga',
  PROTECTOR: 'Protector',
  CLUSTER_BAG: 'Cluster Bag',
  PESTICIDE: 'Pesticida',
  STAPLE: 'Grapa',
  STRIPPING: 'Zuncho',
  THERMOGRAPH: 'Termógrafo',
  SEAL: 'Sello',
  METTO_LABEL: 'Etiqueta Metto',
  LATEX_REMOVER: 'Removedor de Látex',
  INSECTICIDE: 'Insecticida',
  BLOCKING_SHEET: 'Lámina de Bloqueo',
  STICKER: 'Sticker',
  SHEET: 'Hoja',
  CONTAINER_SEAL_PLASTIC: 'Plástico de Cierre Contenedor',
  SECURITY_KIT: 'Kit de Seguridad',
  BOARDING_CARD: 'Tarjeta de Embarque',
};
