import { BlockingSheetType } from './additions/blockingSheet';
import { BoardingCardType } from './additions/boardingCard';
import { ContainerSealPlasticType } from './additions/containerSealPlastic';
import { InsecticideCocktailPart } from './additions/insecticideCocktailPart';
import { LatexRemoverType } from './additions/latexRemover';
import { SecurityKitType } from './additions/securityKit';
import { SheetCocktail } from './additions/sheet';
import { StickerCocktail } from './additions/sticker';
import { MettoLabelType } from './container/mettoLabel';
import { SealType } from './container/seal';
import { StapleType } from './container/staple';
import { StrippingType } from './container/stripping';
import { ThermographType } from './container/thermograph';
import { BandType } from './materials/band';
import { BottomType } from './materials/bottom';
import { CardboardType } from './materials/cardboard';
import { ClusterBagType } from './materials/clusterBag';
import { CornerType } from './materials/corner';
import { CoverType } from './materials/cover';
import { LabelType } from './materials/label';
import { LidType } from './materials/lid';
import { MiniPalletType } from './materials/minipallet';
import { PackingTapeType } from './materials/packingtape';
import { PadType } from './materials/pad';
import { PalletType } from './materials/pallet';
import { ParasealType } from './materials/paraseal';
import { ProtectorType } from './materials/protector';
import { ReinforcementType } from './materials/reinforcement';
import { RubberType } from './materials/rubber';
import { SachetType } from './materials/sachet';
import { SpongeType } from './materials/sponge';
import { PesticideCocktailPart } from './post-harvest/pesticideCocktailPart';
import { BrandType } from './specifications/brand';

export type BoxBrandType = {
  id?: number | '';
  // specifications
  brand?: Partial<BrandType>;
  brandId: number | '';
  name: string;
  brandCode: string;
  boxQuantity: number | '';
  netWeightBox: number | '';
  grossWeightBox: number | '';
  requiredCertificates: number[] | null | string[];
  // materials
  bottomType?: Partial<BottomType>;
  bottomTypeId: number | '';
  bottomTypeQuantity: number | '';
  lidType?: Partial<LidType>;
  lidTypeId: number | '';
  lidTypeQuantity: number | '';
  coverType?: Partial<CoverType>;
  coverTypeId: number | '';
  coverTypeQuantity: number | '';
  cardboardType?: Partial<CardboardType>;
  cardboardTypeId: number | '';
  cardboardTypeQuantity: number | '';
  parasealType?: Partial<ParasealType>;
  parasealTypeId?: number | '';
  parasealTypeQuantity: number | '';
  padType?: Partial<PadType>;
  padTypeId?: number | '';
  padTypeQuantity: number | '';
  spongeType?: Partial<SpongeType>;
  spongeTypeId?: number | '';
  spongeTypeQuantity: number | '';
  label?: Partial<LabelType>;
  labelId: number | '';
  labelQuantity: number | '';
  band?: Partial<BandType>;
  bandId: number | '';
  bandQuantity: number | '';
  sachet?: Partial<SachetType>;
  sachetId: number | '';
  sachetQuantity: number | '';
  rubber?: Partial<RubberType>;
  rubberId: number | '';
  rubberQuantity: number | '';
  protector?: Partial<ProtectorType>;
  protectorId: number | '';
  protectorQuantity: number | '';
  clusterBag?: Partial<ClusterBagType>;
  clusterBagId: number | '';
  clusterBagQuantity: number | '';
  // post harvest
  pesticideCocktail?: Partial<PesticideCocktailPart>[];
  palletsType?: Partial<PalletType>;
  palletsTypeId?: number | '';
  palletsTypeQuantity: number | '';
  miniPalletsType?: Partial<MiniPalletType>;
  miniPalletsTypeId?: number | '';
  miniPalletsTypeQuantity: number | '';
  cornerType?: Partial<CornerType>;
  cornerTypeId?: number | '';
  cornerTypeQuantity: number | '';
  reinforcementType?: Partial<ReinforcementType>;
  reinforcementTypeId?: number | '';
  reinforcementTypeQuantity: number | '';
  staple?: Partial<StapleType>;
  stapleId: number | '';
  stapleQuantity: number | '';
  stripping?: Partial<StrippingType>;
  strippingId: number | '';
  strippingQuantity: number | '';
  thermograph?: Partial<ThermographType>;
  thermographId: number | '';
  thermographQuantity: number | '';
  seal?: Partial<SealType>;
  sealId: number | '';
  sealQuantity: number | '';
  mettoLabel?: Partial<MettoLabelType>;
  mettoLabelId: number | '';
  mettoLabelQuantity: number | '';
  // additions
  packingTapeType?: Partial<PackingTapeType>;
  packingTapeTypeId?: number | '';
  packingTapeTypeQuantity: number | '';
  latexRemover?: Partial<LatexRemoverType>;
  latexRemoverId: number | '';
  latexRemoverQuantity: number | '';
  blockingSheet?: Partial<BlockingSheetType>;
  blockingSheetId: number | '';
  blockingSheetQuantity: number | '';
  containerSealPlastic?: Partial<ContainerSealPlasticType>;
  containerSealPlasticId: number | '';
  containerSealPlasticQuantity: number | '';
  securityKit?: Partial<SecurityKitType>;
  securityKitId: number | '';
  securityKitQuantity: number | '';
  boardingCard?: Partial<BoardingCardType>;
  boardingCardId: number | '';
  boardingCardQuantity: number | '';
  insecticideCocktail?: Partial<InsecticideCocktailPart>[];
  stickerCocktail?: Partial<StickerCocktail>[];
  sheetCocktail?: Partial<SheetCocktail>[];
};
